#!/bin/bash

set -e

echo "Starting server..."
nohup benito/run.sh prod &
PID=$!
sleep 30
echo $PID > process

curl localhost:80/heart-beat

if [ $? -eq 0];
then
  echo "Server started correctly!"
else
  echo "Server failed to start"
  exit -1
fi

